spring:
  application:
    name: demo-client

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    tags:
      application: demo-client
